#! /bin/bash
#
# Clone a stacks database into a local database for developmen
#

if [[ -z $1 ]]; then
    echo "Error: Must provide stack name"
    echo
    echo "./clone <stack>"
    echo
    exit 1
fi

set -euo pipefail

DB=$(deploy info $1 | jq -rc .Outputs.DB)

pg_dump --verbose --schema public -Fc "$DB" > /tmp/oa-$1-out.sql

echo "
    DROP DATABASE openaddresses;
    CREATE DATABASE openaddresses;
" | psql -U postgres

echo "
    CREATE EXTENSION POSTGIS;
" | psql -U postgres openaddresses

pg_restore -U postgres -d openaddresses < /tmp/oa-$1-out.sql
