#! /bin/bash

set -euo pipefail

test() {
    cd $1
    npm install
    npm run lint
    npm run cov || npm test
    cd -
}

echo "CREATE DATABASE openaddresses_test" | psql "postgres://postgres@localhost:5432"

test .
test api/
