#! /bin/bash

set -euo pipefail

test() {
    cd $1
    yarn install
    yarn lint
    yarn cov || yarn test
    cd -
}

echo "CREATE DATABASE openaddresses_test" | psql "postgres://postgres@localhost:5432"

test .
test api/
test task/
